#! /bin/bash

set -e


if [ $EUID -ne 0 ]; then
	echo "$(basename $0) must be run as root"
	exit 1
fi

if ! aldm-release > /dev/null; then
	echo "Not currently running a aldm deployment"
	exit 1
fi

MOUNT_PATH=/aldm_root

if ! mountpoint -q ${MOUNT_PATH}; then
        mkdir -p ${MOUNT_PATH}
        mount -L aldm_root ${MOUNT_PATH}
        sleep 5
fi

if ! mountpoint -q ${MOUNT_PATH}/boot && ls -1 /dev/disk/by-label | grep EFI > /dev/null; then
        mkdir -p ${MOUNT_PATH}/boot
        mount -L EFI ${MOUNT_PATH}/boot
        sleep 5
fi

DEPLOYMENT=$(aldm-release)

# set to read-write mode
mount -o remount,rw /
btrfs property set -fts /aldm_root/deploys/${DEPLOYMENT} ro false
sed -i -e 's/,ro,/,rw,/' /etc/fstab
systemctl daemon-reload


# move kernel/initrd and ucode to standard location
BOOT_CFG="${MOUNT_PATH}/boot/loader/entries/aldm.conf"
if [ -f "${BOOT_CFG}" ]; then
	# guard is for compatibility with systems still using syslinux during the transition to systemd-boot
	cp ${MOUNT_PATH}/boot/${DEPLOYMENT}/* ${MOUNT_PATH}/boot/
	sed -i ${BOOT_CFG} -e s,/${DEPLOYMENT}/,/,g
fi


# copy package database and refresh
if [ -d /usr/var/lib/pacman/local ] && [ ! -d /var/lib/pacman/local ]; then
	mkdir -p /var/lib/pacman
	cp -r /usr/var/lib/pacman/local /var/lib/pacman/
	pacman -Sy
fi

echo "aldm deployment ${DEPLOYMENT} unlocked"
