#!/bin/bash

set -e
set -o pipefail

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi


ARGUMENTS=$1


if [[ $ARGUMENTS == "--check" ]]; then
    echo "Checking for Updates..."
    python3 scripts/check.py
elif [ -n $ARGUMENTS ]; then
    echo "Starting upgrade..."
    python3 scripts/upgrade.py
fi
